//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdmission()
        {
            this.tblSectionAllocations = new HashSet<tblSectionAllocation>();
            this.tblClassFeeDetails = new HashSet<tblClassFeeDetail>();
            this.tblFeeCollections = new HashSet<tblFeeCollection>();
            this.tblPromoteToClasses = new HashSet<tblPromoteToClass>();
            this.tblAttendances = new HashSet<tblAttendance>();
        }
    
        public int AdmissionId { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<decimal> TotalFees { get; set; }
        public Nullable<decimal> FeeToBePaid { get; set; }
        public Nullable<decimal> RegistrationFees { get; set; }
        public string FeeIncharge { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> BalanceAmountDue { get; set; }
        public string NoOfInstallments { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string EnquiryStatus { get; set; }
        public string InSectionStatus { get; set; }
        public string Reason { get; set; }
        public string Photo { get; set; }
        public string Resume { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblEnquiryDetail tblEnquiryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSectionAllocation> tblSectionAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClassFeeDetail> tblClassFeeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeeCollection> tblFeeCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPromoteToClass> tblPromoteToClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendance> tblAttendances { get; set; }
    }
}
