//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendance
    {
        public int AttendanceId { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public int AdmissionId { get; set; }
        public int SectionId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string Attendance { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblAdmission tblAdmission { get; set; }
        public virtual tblEnquiryDetail tblEnquiryDetail { get; set; }
    }
}
