//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnquiryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEnquiryDetail()
        {
            this.tblAdmissions = new HashSet<tblAdmission>();
            this.tblSectionAllocations = new HashSet<tblSectionAllocation>();
            this.tblFeeCollections = new HashSet<tblFeeCollection>();
            this.tblPromoteToClasses = new HashSet<tblPromoteToClass>();
            this.tblAttendances = new HashSet<tblAttendance>();
        }
    
        public int EnquiryId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public string Village { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string AadharNumber { get; set; }
        public string Landline { get; set; }
        public string Qualification { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string HowToKnowUs { get; set; }
        public string ReferredBy { get; set; }
        public string SchoolName { get; set; }
        public string CounsellorName { get; set; }
        public string FollowUpComment { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string Comments { get; set; }
        public string PinCode { get; set; }
        public string Others { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdmission> tblAdmissions { get; set; }
        public virtual tblClass tblClass { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblSection tblSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSectionAllocation> tblSectionAllocations { get; set; }
        public virtual tblSession tblSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeeCollection> tblFeeCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPromoteToClass> tblPromoteToClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendance> tblAttendances { get; set; }
    }
}
