//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPromoteToClass
    {
        public int PromoteToClassId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public Nullable<int> AdmissionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> LastClassId { get; set; }
        public string RollNo { get; set; }
        public string Status { get; set; }
        public string RecordStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual tblAdmission tblAdmission { get; set; }
        public virtual tblClass tblClass { get; set; }
        public virtual tblEnquiryDetail tblEnquiryDetail { get; set; }
        public virtual tblSection tblSection { get; set; }
        public virtual tblSession tblSession { get; set; }
    }
}
